main:
#TOP LEVEL
  - name: Rampe de Lancement
    pageRef: /
    weight: 1
    identifier: home

#TOP LEVEL
  - name: Services
    identifier: services
    weight: 2
  # LEVEL 1
  - name: Experimentation
    parent: services
    pageRef: /services/experimentation
    weight: 1
  - name: Calcul sur demande
    parent: services
    pageRef: /services/calcul-sur-demande
    weight: 2

#TOP LEVEL
  - name: A Propos
    identifier: about
    weight: 3
  # LEVEL 1
  - name: A Propos
    parent: about
    pageRef: /a-propos
    weight: 1
  - name: Glossaire
    parent: about
    pageRef: /glossaire
    weight: 2
  - name: Termes & Conditions
    parent: about
    pageRef: /termes-conditions
    weight: 3
  - name: Politiques
    parent: about
    pageRef: /politiques
    weight: 4
  - name: Contactez Nous
    parent: about
    pageRef: /contactez-nous
    weight: 5

#TOP LEVEL
  - name: Information
    identifier: information
    weight: 4
  # LEVEL 1
  - name: AWS
    identifier: information-aws
    parent: information
    pageRef: /information/aws
    weight: 2
  - name: Azure
    identifier: information-azure
    parent: information
    pageRef: /information/azure
    weight: 3
  - name: GCP
    identifier: information-gcp
    parent: information
    pageRef: /information/gcp
    weight: 4
  - name: General
    identifier: information-general
    parent: information
    pageRef: /information/general
    weight: 1

#TOP LEVEL
  - name: Tutoriels
    identifier: tutorials
    pageRef: /tutoriels
    weight: 5
  # LEVEL 1
  - name: AWS
    identifier: tutorials-aws
    parent: tutorials
    pageRef: /tutoriels/aws
    weight: 2
  - name: Azure
    identifier: tutorials-azure
    parent: tutorials
    pageRef: /tutoriels/azure
    weight: 3
  - name: GCP
    identifier: tutorials-gcp
    parent: tutorials
    pageRef: /tutoriels/gcp
    weight: 4
  - name: General
    identifier: tutorials-general
    parent: tutorials
    pageRef: /tutoriels/general
    weight: 1
