main:
#TOP LEVEL
  - name: LaunchPad
    pageRef: /
    weight: 1
    identifier: home
  - name: Services
    identifier: services
    weight: 2
  - name: About
    identifier: about
    weight: 3


  # LEVEL 1 - Services
  - name: Experimentation
    parent: services
    pageRef: /services/experimentation
    weight: 1
  - name: Roadmap
    parent: services
    pageRef: /services/roadmap
    weight: 10

  # LEVEL 1 - About Us
  - name: About Us
    parent: about
    pageRef: /about-us
    weight: 1
  - name: Case Studies
    parent: about
    pageRef: /about-us/case-studies
    weight: 2
  - name: Terms & Conditions
    parent: about
    pageRef: /terms-conditions
    weight: 3
  - name: Policies
    parent: about
    pageRef: /policies
    weight: 4
  - name: Contact Us
    parent: about
    pageRef: /about-us/contact-us
    weight: 5

private:
#TOP LEVEL
  # LEVEL 1
  - name: Tutorials
    identifier: tutorials
    pageRef: /tutorials
    weight: 1
  - name: Information
    identifier: information
    pageRef: /information
    weight: 2

  # LEVEL 2 - Tutorials
  - name: General
    identifier: tutorials-general
    parent: tutorials
    pageRef: /tutorials/general
    weight: 1
  - name: AWS
    identifier: tutorials-aws
    parent: tutorials
    pageRef: /tutorials/aws
    weight: 2
  - name: Azure
    identifier: tutorials-azure
    parent: tutorials
    pageRef: /tutorials/azure
    weight: 3
  - name: GCP
    identifier: tutorials-gcp
    parent: tutorials
    pageRef: /tutorials/gcp
    weight: 4

  # LEVEL 2 - Information
  - name: General
    identifier: information-general
    parent: information
    pageRef: /information/general
    weight: 1
  - name: AWS
    identifier: information-aws
    parent: information
    pageRef: /information/aws
    weight: 2
  - name: Azure
    identifier: information-azure
    parent: information
    pageRef: /information/azure
    weight: 3
  - name: GCP
    identifier: information-gcp
    parent: information
    pageRef: /information/gcp
    weight: 4
